server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.34.54.136:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: cquisbackend
    password: sidhdzkdl

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true

logging:
  level:
    sql: debug